trigger:
  branches:
    include:
      - main

pool:
  name: default

jobs:
  - job: BuildAndRun
    displayName: "Build and Run Application in Docker (Staging)"
    steps:
      - script: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
        displayName: "Instalar dependências"

      - task: Docker@2
        displayName: "Build Docker image"
        inputs:
          command: "build"
          Dockerfile: "./Dockerfile"
          tags: "supermercado-api:latest"
          repository: "supermercado-api"

      - script: |
          docker run -d -p 8080:8080 --name supermercado-test-container supermercado-api:latest
          sleep 10
          curl --fail http://localhost:8080 || (echo "App não subiu corretamente" && docker logs supermercado-test-container && exit 1)
          docker stop supermercado-test-container
          docker rm supermercado-test-container
        displayName: "Run container and check health"
