trigger:
  branches:
    include:
      - main

pool:
  name: default

jobs:
  - job: Test
    displayName: 'Run API Tests'
    steps:
      - script: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
        displayName: 'Install dependencies'
      
      - script: |
          source .venv/bin/activate
          python3 -m flask run --port 5000 &
          sleep 10  # Dá tempo para o servidor iniciar
        displayName: 'Start Flask server'
      
      - script: |
          source .venv/bin/activate
          python3 tests/test_api_script.py
        displayName: 'Run tests'