trigger:
  branches:
    include:
      - main

pool:
  name: default

jobs:
  - job: Setup
    displayName: 'Setup'
    steps:
      - script: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
        displayName: 'Setup'
  - job: Lint
    displayName: 'Run Lint Test'
    steps: 
      - script: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install flake8
          flake8 src/ super/
        displayName: 'Run Lint (flake8)'