trigger:
  branches:
    include:
      - main

pool:
  name: default

jobs:
  - job: LintTest
    displayName: "Run Lint Test"
    steps:
      - script: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
        displayName: "Install dependencies"

      - script: |
          source .venv/bin/activate
          find . -type f -name "*.py" ! -path "./.venv/*" ! -path "*/__pycache__/*" | xargs flake8
        displayName: "Run Lint (flake8)"

  - job: TestAPI
    displayName: "Run API Tests"
    dependsOn: LintTest
    steps:
      - script: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
        displayName: "Install dependencies"

      - script: |
          source .venv/bin/activate
          python3 -m flask run --port 5000 &
          sleep 10
        displayName: "Start Flask server"

      - script: |
          source .venv/bin/activate
          python3 tests/teste_api.py
        displayName: "Run tests"

  - job: BuildAndRun
    displayName: "Build and Run Application in Docker (Staging)"
    dependsOn: TestAPI
    steps:
      - script: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
        displayName: "Instalar dependências"

      - task: Docker@2
        displayName: "Build Docker image"
        inputs:
          command: "build"
          repository: "supermercado-api"
          Dockerfile: "Dockerfile"
          tags: |
            latest

      - script: |
          docker run -d -p 8080:5000 --name supermercado-test-container supermercado-api:latest
          echo "Aguardando o container subir..."
          sleep 10

          echo "Verificando se a aplicação está no ar..."
          if curl --fail -s http://localhost:8080 > /dev/null; then
            echo "App respondeu com sucesso!"
          else
            echo "App não subiu corretamente"
            docker logs supermercado-test-container
            exit 1
          fi

          docker stop supermercado-test-container
          docker rm supermercado-test-container
        displayName: "Run container and check health"

  - job: Locust
    displayName: "Performance Test"
    dependsOn: BuildAndRun
    steps:
      - script: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
        displayName: "Instalar dependências"

      - script: |
          source .venv/bin/activate
          python3 -m flask run --port 5000 &
          sleep 10
        displayName: "Start Flask server"

      - script: |
          source .venv/bin/activate
          locust -f tests/locustfile.py --host=http://localhost:5000 --headless -u 10 -r 2 -t15s
        displayName: "Run Locust"
