trigger:
  branches:
    include:
      - main

pool:
  name: default

jobs:
  - job: Setup
    displayName: 'Setup'
    steps:
      - script: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
        displayName: 'Setup'
  - job: 'ConsumidorTest'
    displayName: 'Run Consumidor API Test'
    steps:
      - script: |
          python3 -m venv .venv
          source .venv/bin/activate
          python3 tests/test_api_script.py
        displayName: 'Run Consumidor API Test'