trigger:
  branches:
    include:
      - main

pool:
  name: default

jobs:
  - job: Locust
    displayName: "Performance Test"
    steps:
      - script: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
        displayName: "Instalar dependências"

      - script: |
          source .venv/bin/activate
          python3 -m flask run --port 5000 &
          sleep 10
        displayName: "Start Flask server"

      - script: |
          locust -f tests/locustfile.py --host=http://localhost:5000 --headless -u 10 -r 2 -t 30s
        displayName: "Run Locust"
