apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-config
  namespace: {{ .Values.namespace }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.prometheus.config.scrape_interval }}

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'aks-kubelet'
        scheme: https
        tls_config:
          insecure_skip_verify: true
        authorization:
          credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        static_configs:
          - targets: ['aks-agentpool-34936449-vmss000000:10250']
        metrics_path: '/metrics/cadvisor'
        relabel_configs:
          - source_labels: [__address__]
            target_label: instance
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)

      - job_name: 'py-prom'
        metrics_path: /metrics
        static_configs:
          - targets: ['py-prom-svc.{{ .Values.namespace }}.svc.cluster.local:80']
