apiVersion: v1
kind: Service
metadata:
  name: prom-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: {{ .Values.prometheus.service.port }}
      targetPort: {{ .Values.prometheus.service.targetPort }}
  type: {{ .Values.prometheus.service.type }}
