apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: { { .Values.namespace } }
data:
  python-app.json: |-
    {
      "title": "Python App Metrics",
      "panels": [
        {
          "title": "HTTP Requests",
          "type": "graph",
          "targets": [
            {
              "expr": "rate(http_requests_total[5m])",
              "legendFormat": "{{method}} {{endpoint}}"
            }
          ]
        }
      ]
    }
