{{- if and .Values.grafana.enabled .Values.grafana.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.grafana.persistence.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.grafana.persistence.size | default "1Gi" }}
  storageClassName: {{ .Values.grafana.persistence.storageClassName | default "default" | quote }}
{{- end }}