apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: { { .Values.namespace } }
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: { { .Values.grafana.service.port } }
      targetPort: { { .Values.grafana.service.targetPort } }
  type: { { .Values.grafana.service.type } }
