trigger:
  branches:
    include:
      - teste
  paths:
    include:
      - ".azure/pipeline-commit.yml"

pool:
  name: default

jobs:
  - job: LintTest
    displayName: "Run Lint Test"
    steps:
      - script: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
        displayName: "Install dependencies"

      - script: |
          source .venv/bin/activate
          find . -type f -name "*.py" ! -path "./.venv/*" ! -path "*/__pycache__/*" | xargs flake8
        displayName: "Run Lint (flake8)"

  - job: TestAPI
    displayName: "Run API Tests"
    dependsOn: LintTest
    steps:
      - script: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
        displayName: "Install dependencies"

      - script: |
          source .venv/bin/activate
          python3 -m flask run --port 5000 &
          sleep 10
        displayName: "Start Flask server"

      - script: |
          source .venv/bin/activate
          python3 tests/teste_api.py
        displayName: "Run tests"
