name: Python CI

on:
  push:
    branches:
      - teste

jobs:
  lint:
    name: Run Lint Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Run Lint (flake8)
        run: |
          source .venv/bin/activate
          find . -type f -name "*.py" ! -path "./.venv/*" ! -path "*/__pycache__/*" | xargs flake8

  test:
    name: Run API Tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Start Flask server
        run: |
          source .venv/bin/activate
          nohup python3 -m flask run --port 5000 &
          sleep 10

      - name: Run tests
        run: |
          source .venv/bin/activate
          python3 tests/teste_api.py
